name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build passed"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test passed"

  lint:
    runs-on: ubuntu-latest
    steps:
      -run: echo "lint passed"

